kind: Service
apiVersion: v1
metadata:
  name:  Service Name
spec:
  type:   NodePort
  ports:
  - name:  webserver
    port:  80
    targetPort:  80
    nodePort: 30008
  selector:
    app:  myapp
    type: front-end