apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myapp-replicaset
  labels:
    app: myapp
    type: frontend
spec:
  selector: 
    matchLabels:
      app: myapp
  tamplate:
    metadata:
      name: Webserver
      labels:
        name: Webserver
        app: myapp
        type: pod

    spec:
      containers:
        - name: nginx-Container
          image: nginx
  replicas: 3