apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
    labels: 
      app: myapp
      type: back-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels: 
        app: myapp
        type: back-end
    spec:
      containers:
        - name: jboss7
          image: dineshpatel14/jboss7
          ports:
            - containerPort: 8080
            - containerPort: 8009
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      type: back-end