apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment-jboss
    labels: 
      app: jboss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-application
      name: jboss-pod
  template:
    metadata:
      name: jboss-pod
      labels: 
        app: test-application
        name: jboss-pod 
    spec:
      containers:
        - name: jboss
          image: dineshpatel14/jboss7
          ports:
            - containerPort: 8080
            - containerPort: 8009
          resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "600m"