apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
    labels: 
      app: myapp
      type: front-end
spec:
  template:
    metadata:
      name: myapp-pod-web
      labels: 
        app: myapp-web
        type: front-end
    spec:
      containers:
        - name: webserver
          image: dineshpatel14/webserver
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
  replicas: 2
  selector:
    matchLabels:
      app: myapp-web
      type: front-end