apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment-web
    labels: 
      app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-application
      name: webserver-pod
  template:
    metadata:
      name: webserver-pod
      labels: 
        app: test-application
        name: webserver-pod
    spec:
      containers:
        - name: webserver
          image: dineshpatel14/webserver
          ports:
            - containerPort: 80
            - containerPort: 7200
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
