apiVersion: v1
kind: Service
metadata:
  name: jboss7-service-cluster
  labels:
    name: myapp-jboss-service
    app: myapp
spec:
  selector:
      app: myapp
      type: back-end
  ports:
    - port: 8080
      targetPort: 8080