apiVersion: v1
kind: Service
metadata:
  name: jboss
  labels:
    name: myapp-service-jboss
    app: test-application
spec:
  selector:
      app: test-application
      name: jboss-pod
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: ajp
      port: 8009
      targetPort: 8009