apiVersion: v1
kind: Service
metadata:
  name: jboss7-service-lb
spec:
  selector:
      app: myapp-jboss
      type: back-end
  ports:
    - port: 8080
      targetPort: 8080
      
  type: LoadBalancer
