apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    name: webserver-service
    app: test-application
spec:
  selector:
      app: test-application
      name: webserver-pod
  ports:
    - port: 7200
      targetPort: 7200