apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    name: myapp-jboss-service
    app: myapp
spec:
  selector:
      app: myapp
      type: back-end
  ports:
    - port: 7200
      targetPort: 7200