apiVersion: v1
kind: Service
metadata:
  name: webserver-service-lb
spec:
  selector:
      app: test-application
      name: webserver-pod
  ports:
    - port: 80
      targetPort: 80
      
  type: LoadBalancer
