apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp
    type: back-end

spec:
  containers:
    - name: jboss-server
      image: dineshpatel14/jboss7
      ports:
       - containerPort: 8080
